name: Twilio Sned
on:
  workflow_dispatch: # allows you to manually trigger the workflow
env:
    TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
    TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
    TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
permissions:
  contents: read
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: ${{ secrets.FROM_PHONE }} # alternatively, use a Repository Secret
          toPhoneNumber: ${{ secrets.TO_PHONE }} # alternatively, use a Repository Secret
          message: 'Hello from Twilio'
